version: '3.8'

services:
  db_mysql:
    image: mysql:8.0
    cap_add:
      - SYS_NICE
    restart: always
    environment:
      - MYSQL_DATABASE=DatabaseName
      - MYSQL_ROOT_PASSWORD=DatabasePassword
    ports:
      - '3307:3306'
    volumes:
      - ./db/mysql:/var/lib/mysql
      #- ./db/init.sql:/docker-entrypoint-initdb.d/init.sql
    profiles:
      - e2e-test
      - local
      - db_mysql

  db_postgres:
    image: postgres:latest
    environment:
      POSTGRES_DB: DatabaseName
      POSTGRES_USER: DatabaseUser
      POSTGRES_PASSWORD: DatabasePassword
    ports:
      - "5433:5432"
    volumes:
      - ./db/postgres:/var/lib/postgresql/data
      - "./apps/backend/scripts/init-db.sql:/docker-entrypoint-initdb.d/init-db.sql"
    profiles:
      - e2e-test
      - local
      - db_postgres

volumes:
  db_mysql:
    driver: local

  db_postgres:
    driver: local
