version: '3.8'

services:
  restaurant_scrape_db:
    image: mysql:8.0
    cap_add:
      - SYS_NICE
    restart: always
    environment:
      - MYSQL_DATABASE=DatabaseName
      - MYSQL_ROOT_PASSWORD=DatabasePassword
    ports:
      - '3306:3306'
    volumes:
      - ./db/data:/var/lib/mysql
      #- ./db/init.sql:/docker-entrypoint-initdb.d/init.sql
    profiles:
      - e2e-test
      - local
      - db

volumes:
  db:
    driver: local
